apiVersion: v1
kind: Service
metadata:
  name: pythonrestapi-service
  labels: 
    app: pythonrestapi-app
spec:
  type: LoadBalancer
  selector:
    app: pythonrestapi-app
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 5000