apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonrestapi-deployment
  labels:
    app: pythonrestapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonrestapi-app
  template:
    metadata:
      labels:
        app: pythonrestapi-app
    spec:
      containers:
      - name: pythonrestapi-container
        image: yhines/pythonrestapi:0.0.1RELEASE
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000