############################################
#       Build Docker Image with App        #
#           By: Yasmine Hines              #
#            Date: 1/3/2023                #
############################################
name: Build Deploy and Cleanup

on:
  workflow_dispatch:

jobs: 
  buildAndDeploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      # Log in with your Docker account 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the python app into a Docker image
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./pythonrestapi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pythonrestapi:0.0.2

      # Log in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

       # Install kubectl to use for deploying app to AKS
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.3'
        id: install

      # Deploy Docker image in my AKS cluster
      - name: Deploy Docker Image
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: |
          ${{ secrets.CONFIG }}
          ${{ secrets.DIRECTORY }}
          kubectl apply -f pythonrestapi-deployment.yaml
          kubectl apply -f pythonrestapi-service.yaml
          sleep 45s
          externalIp=$(kubectl get svc pythonrestapi-service -n default -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
          echo "http://$externalIp:80" 
          curl "http://$externalIp:80" 

      - name: verifyApp
        run: |
          sleep 45s

      - name: Cleanup AKS Cluster
        run: |
          ${{ secrets.CONFIG }}
          kubectl delete services pythonrestapi-service
          kubectl delete deployment pythonrestapi-deployment