############################################
#       Build Docker Image with App        #
#           By: Yasmine Hines              #
#            Date: 1/3/2023                #
############################################
name: Build Docker Image

on:
  push:
    branches:
    - deployment
  workflow_dispatch:

jobs: 
  buildDockerImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      # Log in with your Docker account 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the python app into a Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./pythonrestapi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pythonrestapi:0.0.2

      # Call the next workflow - Deploy App to AKS
  
  callWorkflowDeploy:
    needs: buildDockerImage
    permissions:
      contents: read
      id-token: write
    uses: Yrh004/BuildTestApplication/.github/workflows/deploy-app-aks.yaml@deployment

  callWorkflowCleanup:
    needs: callWorkflowDeploy
    permissions:
      contents: read
      id-token: write
    uses: Yrh004/BuildTestApplication/.github/workflows/cleanup-aks-cluster.yaml@deployment