############################################
#          Cleanup AKS Cluster             #
#           By: Yasmine Hines              #
#            Date: 1/3/2023                #
############################################
name: Cleanup AKS Cluster

on:
  push:
    branches:
    - deployment
  # workflow_call:

env: 
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:  
  cleanUp:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps: 
      - name: verifyApp
        run: |
          sleep 60s

       # Install kubectl to use for deploying app to AKS
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.3'
        id: install

      - name: Cleanup AKS Cluster
        run: |
          ${{ secrets.CONFIG }}
          kubectl cluster-info
          # kubectl delete services pythonrestapi-service
          # kubectl delete deployment pythonrestapi-deploy