############################################
#          Cleanup AKS Cluster             #
#           By: Yasmine Hines              #
#            Date: 1/3/2023                #
############################################
name: Cleanup AKS Cluster

on:
  workflow_call:

env: 
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:  
  cleanUp:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps: 
      - name: verifyApp
        run: |
          sleep 60s

      - name: Cleanup AKS Cluster
        run: |
          kubectl delete services pythonrestapi-service
          kubectl delete deployment pythonrestapi-deploy