############################################
#          Cleanup AKS Cluster             #
#           By: Yasmine Hines              #
#            Date: 1/3/2023                #
############################################
name: Cleanup AKS Cluster

on:
  workflow_call:

env: 
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:  
  cleanUp:
    runs-on: ubuntu-latest
    steps: 
      - name: verifyApp
        run: |
          externalIP=$(kubectl get svc pythonrestapi-service -n default -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
          port=$(kubectl describe service pythonrestapi-service | grep -i nodeport)
          curl http://$externalIP:port

      - name: Cleanup AKS Cluster
        run: |
          kubectl delete services pythonrestapi-service
          kubectl delete deployment pythonrestapi-deploy