name: Deploy App to AKS

on:
  push:
    branches:
    - deployment

env:
  RESOURCE_GROUP: "Demo_Resoure_Group"
  CLUSTER_NAME: "demoAKSCluster"


jobs:
  deployAppToAks:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.3'
        id: install

      - uses: actions/checkout@v2
      - name: Azure Login using OIDC
        uses: ./.github/workflows/composite/azure-oidc-login
        with:
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run az commands'
      run: |
        az account show

      # - name: Azure CLI Action
      #   uses: Azure/cli@v1.0.7
      #   with:
      #     # Specify the script here
      #     inlineScript: |
      #       az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #       az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}

      # - name: Build, tag, and push image to Docker
      #   run: |
      #     docker build -t yhines/pythonrestapi:0.0.2 ./Kubernetes/deployment
      #     docker push -a yhines/pythonrestapi:0.0.2

      # - name: Deployment
      #   run: |
      #     kubectl apply -f pythonrestapi-deployment.yaml
      #     kubectl apply -f pythonrestapi-service.yaml